const SELECT_NURSERY = "SELECT_NURSERY";
const ADD_SAPLING = "ADD_SAPLING";
const SUBTRACT_SAPLING = "SUBTRACT_SAPLING";
const INITIALIZE_STATE = "INITIALIZE_STATE";

export { SELECT_NURSERY, ADD_SAPLING, SUBTRACT_SAPLING, INITIALIZE_STATE };
